### ISSUE TITLE
Throws an error in older Firefox versions

### ISSUE THREAD

**Issue by kurtextrem** [filamentgroup/woff2-feature-test#12]
"win.FontFace is not a constructor."
http://prntscr.com/9425z4

**Comment by zachleat** [comment]
Which versions does this apply to?

I tested Firefox 34, 39, 40 and they all reported false (as expected due to no CSS Font Loading API) but no error.

In your screenshot you’re calling this manually, which will give an error (as expected)—this constructor function is part of the CSS Font Loading API.

I think this is an incorrect report. Please reopen if you disagree!

**Comment by kurtextrem** [comment]
Old firefox version means as old as firefox 4, 5, 6

**Comment by zachleat** [comment]
Looks ok to me: 
![image](https://cloud.githubusercontent.com/assets/39355/17227709/43a336c6-54d5-11e6-89d5-d4daadf66340.png)

Again, keep in mind that this feature test uses the CSS Font Loading API, which has its own browser support: http://caniuse.com/#feat=font-loading

**Comment by kurtextrem** [comment]
weird, I had that problem on a live system. Will see if I can reproduce tomorrow :)

**Comment by zachleat** [comment]
Thanks @kurtextrem!

**Comment by kurtextrem** [comment]
I haven't tested Firefox 4 yet, but I've tested which errors are which ones: http://prntscr.com/byydhu (in most recent Chrome)

What I notice:
- if is a constructor, it will return an error saying no/not enough arguments given
- if it isn't a constructor, it will say `prop is not a constructor`

My Firefox console screenshot shows the second case, which means the property `FontFace` is not a function in that browser, but rather a property (object) and therefore unsupported. Which also means we need to check if `FontFace` is a function (and can be used a constructor) or it throws the error I've screenshoted.

**Comment by zachleat** [comment]
So, you’re saying the test is giving an incorrect negative in a version of Firefox? Can you provide which version it’s failing in so I can confirm?

**Comment by kurtextrem** [comment]
Neither. Throws an error meaning it breaks all JS that comes after. (the error can't be catched the way we do it; only a try catch would fix that - or my PR)
