### ISSUE TITLE
Question: Why IIFE?

### ISSUE THREAD

**Issue by CanRau** [filamentgroup/woff2-feature-test#16]
Just out of curiosity, why are you using IIFE style instead of just a normal function or function expression?

I'm quite sure you know what you do and there is a reason behind, would love to know it 💃 

Cheers and thanks for sharing this nice feature detection :)

**Comment by zachleat** [comment]
Good question—the IIFE runs only once!

So the whole thing sort of caches the value and becomes `var supportsWoff2 = true;` or `var supportsWoff2 = false;` depending on what the return value is.

If we made it a function, it’d run every time you checked. Given that the support won’t change while you’re browsing around on a page, this seemed like a nice way to do it.

Closing, but feel free to ask more questions if you’d like!

**Comment by CanRau** [comment]
great..thanks for this satisfactory answer :)
