### ISSUE TITLE
Doesn't detect new Edge

### ISSUE THREAD

**Issue by tinovyatkin** [filamentgroup/woff2-feature-test#17]
Doesn't work in new Edge that coming with WOFF2 support, but WITHOUT FontFace API (Microsoft is good for making things different :))

**Comment by kurtextrem** [comment]
link to docs?

**Comment by zachleat** [comment]
Confirmed 
![image](https://cloud.githubusercontent.com/assets/39355/17227385/b7ccbe70-54d3-11e6-94d5-4325705d45f9.png)

**Comment by tinovyatkin** [comment]
In my own workaround I did fetch test inside WOFF2 test as there is no browsers with fetch support but without WOFF2 support. But it's not a feature test for WOFF2 as clear idea:

`
// All browsers with fetch API currently supports Woff2
        if (typeof window.fetch === 'function') result = true;
`

**Comment by vijayaraghavanramanan** [comment]
Same for Firefox 39-40 I guess. 

http://caniuse.com/#feat=font-loading

http://caniuse.com/#feat=woff2

**Comment by vijayaraghavanramanan** [comment]
Can Adobe Blank (or a 1-character subset of it) be used to detect WOFF2? Create some hidden thing with @font-face using woff2 only and test its length with JS?

**Comment by zachleat** [comment]
Similar to what @vijayaraghavanramanan proposed, we could use the same approach that font loading polyfills (like fontfaceonload or fontfaceobserver) use, which is to measure the size of element with and without a WOFF2 `font-family` applied. This would increase the file size/complexity of the feature test quite a bit though.

**Comment by vijayaraghavanramanan** [comment]
I think it should be easier than fontfaceonload or fontfaceobserver. The property of Adobe Blank is that if it is used the width of a DOM element is zero. So you include a WOFF2 datauri of a single glyph of Adobe Blank and test the width. If it is zero, woff2 is supported. If not, woff2 is not supported.
