### ISSUE TITLE
Unhandled promise rejection in Chrome

### ISSUE THREAD

**Issue by teodragovic** [filamentgroup/woff2-feature-test#4]
Not sure if this is Chrome bug or something else but since latest browser update (v 40.0.2214.91 m), Chrome started displaying "Unhandled promise rejection" (I checked in Firefox and Opera and there where no errors so it's only Chrome for now). Apparently, this happens because promise that `load()` method returns gets network error that is unhandled.

I fixed this by modifying following line but still not sure why this started happending:

`f.load().catch(function(){});`

**Comment by zachleat** [comment]
Related: https://code.google.com/p/v8/issues/detail?id=3093

**Comment by zachleat** [comment]
Thank you!

**Comment by teodragovic** [comment]
:+1: 

Glad I could help.
