### ISSUE TITLE
Passing the test triggers a waring in Chrome.

### ISSUE THREAD

**Issue by baamenabar** [filamentgroup/woff2-feature-test#5]
When run on Chrome it triggers a warning
`Failed to decode downloaded font: data:application/font-woff2, ...`
If you open the console you will see the warning.
Firefox fails the test so it doesn't give the warning.
Happens on Canary too.

This is a minor minor thing, but it had me baffled for about an hour, I thought the problem was from  the fonts I was loading.

You could write a warning about the warning on the on the readme.md or I can do a pull request.

**Comment by MichaelKloepzig** [comment]
I can confirm this for Chromium Version 43.0.2357.130 Ubuntu 14.10 (64-bit).

The test also fails on Firefox 39, which should support Woff2 according to [caniuse.com] (http://caniuse.com/#search=woff2)

**Comment by bitstarr** [comment]
+1 Having same (both) issues.

**Comment by ritchieanesco** [comment]
+1 Is this script still being supported?

**Comment by kurtextrem** [comment]
+1 same here.

**Comment by zachleat** [comment]
Fixed with https://github.com/filamentgroup/woff2-feature-test/pull/8
